# Generated by Django 4.2.4 on 2023-08-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_account_card_payment_charge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountNumber',
            new_name='account_number',
        ),
    ]
